Repository PaddlePaddle/Paddle3D, pull requests merged in 2022-09, with the labels that each got.

#7 [Feature] clean dataset code for caddn model
  configs/caddn/caddn_deeplabv3p_resnet101_os8_kitti.yml
  configs/caddn/caddn_ocrnet_hrnet_w18_kitti.yml
  paddle3d/apis/pipeline.py
  paddle3d/apis/trainer.py
  paddle3d/datasets/__init__.py
  paddle3d/datasets/cadnn_kitti/__init__.py
  paddle3d/datasets/cadnn_kitti/box_utils.py
  paddle3d/datasets/cadnn_kitti/calibration_kitti.py
  paddle3d/datasets/cadnn_kitti/common_utils.py
  paddle3d/datasets/cadnn_kitti/data_processor.py
  paddle3d/datasets/cadnn_kitti/image_augmentor_utils.py
  paddle3d/datasets/cadnn_kitti/kitti_object_eval_python/eval.py
  paddle3d/datasets/cadnn_kitti/kitti_object_eval_python/evaluate.py
  paddle3d/datasets/cadnn_kitti/kitti_object_eval_python/kitti_common.py
  paddle3d/datasets/cadnn_kitti/kitti_object_eval_python/rotate_iou.py
  paddle3d/datasets/cadnn_kitti/object3d_kitti.py
  paddle3d/datasets/kitti/__init__.py
  paddle3d/datasets/kitti/kitti_depth_det.py
  paddle3d/datasets/kitti/kitti_det.py
  paddle3d/datasets/kitti/kitti_metric.py
  paddle3d/datasets/kitti/kitti_utils.py
  paddle3d/geometries/bbox.py
  paddle3d/geometries/pointcloud.py
  paddle3d/models/detection/caddn/caddn.py
  paddle3d/models/detection/caddn/f2v/frustum_grid_generator.py
  paddle3d/models/detection/caddn/f2v/frustum_to_voxel.py
  paddle3d/models/detection/caddn/f2v/sampler.py
  paddle3d/models/detection/caddn/ffe/ddn_loss/__init__.py
  paddle3d/models/detection/caddn/ffe/ddn_loss/balancer.py
  paddle3d/models/detection/caddn/ffe/ddn_loss/ddn_loss.py
  paddle3d/models/detection/caddn/ffe/ffe.py
  paddle3d/models/heads/dense_heads/target_assigner/anchor_generator.py
  paddle3d/models/heads/dense_heads/target_assigner/axis_aligned_target_assigner.py
  paddle3d/models/losses/focal_loss.py
  paddle3d/models/losses/reg_loss.py
  paddle3d/models/losses/weight_loss.py
  paddle3d/transforms/__init__.py
  paddle3d/transforms/functional.py
  paddle3d/utils/box.py
  paddle3d/utils/box_coder.py
  paddle3d/utils/depth.py
  paddle3d/utils/grid.py
  tools/creat_caddn_kitti_infos.py
Labels: enhancement

#70 [Bug Fix] Make SemanticKITTI evaluation API compatible with Trainer code update
  paddle3d/datasets/semantic_kitti/semantic_kitti_metric.py
Labels: bug

#65 [Bug fix] set loaded velocity nan to zero when using nuscenes_devkit<=1.1.9
  paddle3d/datasets/nuscenes/nuscenes_det.py
  requirements.txt
Labels: bug

#72 [Bug Fix] Fix smoke cpp inference demo bug
  deploy/smoke/cpp/infer.cpp
Labels: bug

#77 [Update] remove fluid API
  paddle3d/datasets/base.py
  paddle3d/models/detection/centerpoint/center_head.py
  paddle3d/models/optimizers/optimizers.py
Labels: duplicate, enhancement

#84 [Docs] Add details to the smoke configuration file test=document_fix
  configs/smoke/smoke_dla34_no_dcn_kitti.yml
  configs/smoke/smoke_hrnet18_no_dcn_kitti.yml
Labels: documentation

#90 [Docs] add CaDDN pretrained_model
  docs/models/caddn/README.md
  paddle3d/datasets/kitti/kitti_depth_det.py
Labels: documentation, enhancement
