Repository PaddlePaddle/Paddle3D, pull requests merged in 2022-08, with the labels that each got.

#2 [Feature & Bug Fix] Support train by epoch
  docs/apis/config.md
  docs/apis/trainer.md
  docs/configuration.md
  docs/quickstart.md
  paddle3d/apis/config.py
  paddle3d/apis/scheduler.py
  paddle3d/apis/trainer.py
  tools/train.py
Labels: bug, enhancement

#5 [Feature] Support for building custom op just-in-time
  paddle3d/ops/__init__.py
  paddle3d/ops/setup.py
Labels: enhancement

#19 [Feature] Remove useless ops
  paddle3d/ops/voxelize.py
Labels: enhancement

#20 [Bug Fix] Fix the problem that some codes were not included correctly when packaging
  paddle3d/models/detection/caddn/ffe/ddn_loss/__init__.py
  setup.py
Labels: bug

#21 [Bug Fix] Correct `lidar_record_to_object` description
  paddle3d/datasets/kitti/kitti_utils.py
Labels: bug

#4 [Bug Fix] implement centerpoint preprocess(slice point and pad timelag) with paddle ops during deployment
  deploy/centerpoint/cpp/main.cc
  docs/models/centerpoint/README.md
  paddle3d/models/detection/centerpoint/centerpoint.py
Labels: bug

#22 [Docs] Fix docs error
  README.md
  docs/configuration.md
  docs/models/smoke/README.md
  docs/quickstart.md
Labels: documentation

#23 Add communication info
  README.md
Labels: documentation

#26 [Bug Fix] Fix smoke bug
  docs/models/smoke/README.md
  paddle3d/models/detection/smoke/processor.py
  paddle3d/models/detection/smoke/smoke_coder.py
Labels: bug

#24 [Bug fix] get learning rate before optimizer step
  paddle3d/apis/trainer.py
Labels: bug

#27 [Docs] Refine docs
  docs/models/centerpoint/README.md
  docs/models/pointpillars/README.md
Labels: documentation

#16 [Docs] Unified configuration file naming format
  configs/_base_/kitti_mono.yml
  configs/caddn/caddn_deeplabv3p_resnet101_os8_kitti.yml
  configs/caddn/caddn_ocrnet_hrnet_w18_kitti.yml
  configs/pointpillars/pointpillars_xyres16_kitti_car.yml
  configs/pointpillars/pointpillars_xyres16_kitti_cyclist_pedestrian.yml
  configs/smoke/smoke_dla34_no_dcn_kitti.yml
  configs/smoke/smoke_hrnet18_no_dcn_kitti.yml
  docs/configuration.md
  docs/models/caddn/README.md
  docs/models/pointpillars/README.md
  docs/models/smoke/README.md
  docs/quickstart.md
Labels: documentation

#18 [Feature] Rename transform modules
  paddle3d/transforms/__init__.py
  paddle3d/transforms/anchor_generator.py
  paddle3d/transforms/detection.py
  paddle3d/transforms/normalize.py
  paddle3d/transforms/sampling.py
  paddle3d/transforms/target_generator.py
  paddle3d/transforms/transform.py
Labels: enhancement

#14 [Docs] Add release note
  docs/release_note.md
Labels: documentation

#32 [Bug fix] add is_gpu_pinned() for voxelize custom op
  deploy/centerpoint/cpp/custom_ops/voxelize_op.cc
  deploy/centerpoint/cpp/custom_ops/voxelize_op.cu
  paddle3d/ops/voxel/voxelize_op.cc
  paddle3d/ops/voxel/voxelize_op.cu
Labels: bug

#30 [Docs] Update docs
  configs/caddn/README.md
  configs/pointpillars/README.md
  configs/smoke/README.md
  configs/squeezesegv3/README.md
  docs/models/smoke/README.md
Labels: documentation

#31 [Docs] Update README features
  README.md
Labels: documentation

#38 [Bug Fix] Fix the bugs where gride_size type in voxelize custom op is set as float but supposed to be int
  deploy/centerpoint/cpp/custom_ops/voxelize_op.cu
  paddle3d/ops/voxel/voxelize_op.cu
Labels: bug

#43 [Doc] Update doc
  README.md
  docs/installation.md
Labels: documentation

#59 add python deployment for squeezesegv3
  deploy/squeezesegv3/python/infer.py
  docs/models/squeezesegv3/README.md
Labels: enhancement
