Repository PaddlePaddle/Paddle3D, pull requests merged in 2022-07, with the labels that each got.

#1 [Docs] complete docs
  docs/models/caddn/README.md
  docs/models/centerpoint/README.md
  docs/models/pointpillars/README.md
  docs/models/smoke/README.md
  docs/models/squeezesegv3/README.md
Labels: documentation

#12 [Bug Fix] Fix the bug that EasyDict not throwing AttributeError correctly
  paddle3d/sample.py
Labels: bug

#15 [Docs] Update README
  README.md
Labels: documentation

#17 [Docs] Add apollo link
  docs/models/caddn/README.md
  docs/models/centerpoint/README.md
Labels: documentation

#13 [Bug Fix] Fix smoke eval bug
  configs/smoke/smoke_dla34_no_dcn_iter70000.yml
  configs/smoke/smoke_hrnet18_no_dcn_iter70000.yml
  deploy/smoke/cpp/infer.cpp
  deploy/smoke/python/infer.py
  paddle3d/datasets/kitti/kitti_mono_det.py
  paddle3d/datasets/kitti/kitti_utils.py
  paddle3d/models/detection/smoke/smoke.py
Labels: bug

#8 [Feature] optimize smoke code
  paddle3d/models/detection/smoke/processor.py
  paddle3d/models/detection/smoke/smoke_coder.py
  paddle3d/models/detection/smoke/smoke_loss.py
  paddle3d/models/detection/smoke/smoke_predictor.py
Labels: enhancement
