Repository PaddlePaddle/Paddle3D, pull requests merged in 2022-12, with the labels that each got.

#140 [Bug Fix] Fix centerpoint training bug
  paddle3d/models/optimizers/optimizers.py
Labels: bug

#130 [Feature] Add detection model base class to unify input and output
  configs/caddn/caddn_deeplabv3p_resnet101_os8_kitti.yml
  configs/caddn/caddn_ocrnet_hrnet_w18_kitti.yml
  configs/centerpoint/centerpoint_pillars_016voxel_kitti.yml
  configs/centerpoint/centerpoint_pillars_02voxel_nuscenes_10sweep.yml
  configs/paconv/README.md
  configs/pointpillars/pointpillars_xyres16_kitti_car.yml
  configs/pointpillars/pointpillars_xyres16_kitti_cyclist_pedestrian.yml
  configs/smoke/smoke_dla34_no_dcn_kitti.yml
  configs/smoke/smoke_hrnet18_no_dcn_kitti.yml
  deploy/caddn/python/infer.py
  deploy/smoke/python/infer.py
  docs/models/paconv/README.md
  paddle3d/apis/config.py
  paddle3d/datasets/base.py
  paddle3d/datasets/kitti/kitti_det.py
  paddle3d/datasets/modelnet40/modelnet40_cls.py
  paddle3d/datasets/nuscenes/nuscenes_det.py
  paddle3d/datasets/semantic_kitti/semantic_kitti.py
  paddle3d/datasets/waymo/waymo_det.py
  paddle3d/models/base/__init__.py
  paddle3d/models/base/base_detection.py
  paddle3d/models/base/base_lidar_detection.py
  paddle3d/models/base/base_model.py
  paddle3d/models/base/base_mono_detection.py
  paddle3d/models/classification/paconv/paconv.py
  paddle3d/models/detection/caddn/caddn.py
  paddle3d/models/detection/centerpoint/center_head.py
  paddle3d/models/detection/centerpoint/centerpoint.py
  paddle3d/models/detection/pointpillars/pointpillars.py
  paddle3d/models/detection/pointpillars/pointpillars_head.py
  paddle3d/models/detection/smoke/smoke.py
  paddle3d/models/heads/dense_heads/anchor_head.py
  paddle3d/models/middle_encoders/pillar_scatter.py
  paddle3d/models/segmentation/squeezesegv3/squeezesegv3.py
  paddle3d/models/voxelizers/voxelize.py
  tools/export.py
  tools/graphvis.py
Labels: enhancement

#151 [Docs] Update installation docs
  docs/installation.md
Labels: documentation

#146 [Bug Fix] Fix missing maximum limitation for num_points_in_voxel computed by hard voxelizer custom operation
  deploy/centerpoint/cpp/custom_ops/voxelize_op.cu
  paddle3d/ops/voxel/voxelize_op.cu
Labels: bug

#155 [Docs] Add KITTI mini dataset config for smoke and centerpoint
  configs/centerpoint/centerpoint_pillars_016voxel_kitti_mini.yml
  configs/smoke/smoke_hrnet18_no_dcn_kitti_mini.yml
Labels: documentation

#156 [Bug Fix] Fix smoke vis bug
  deploy/smoke/python/vis.py
Labels: bug

#158 [Bug Fix] Fix wrong soft link of PAConv README
  configs/paconv/README.md
Labels: bug

#164 use predict_boxes_when_training for anchor_head.py
  paddle3d/models/heads/dense_heads/anchor_head.py
Labels: bug

#166 [Docs] Add introduction of PETR
  docs/models/petr/README.md
Labels: documentation

#167 [Docs] Update export docs
  docs/quickstart.md
Labels: documentation

#165 [Bug Fix] Fix the problem of KITTI metric that the evaluation accuracy of the point cloud model is 0
  paddle3d/datasets/kitti/kitti_metric.py
Labels: bug

#168 [Docs] Update model url
  docs/models/centerpoint/README.md
  docs/models/pointpillars/README.md
  docs/models/smoke/README.md
Labels: documentation

#163 clip grad before regularize outside Adam for OneCycleAdam optimizer
  paddle3d/models/optimizers/optimizers.py
Labels: bug

#172 fix error when uniform init bn weight for voxelrcnn
  paddle3d/models/detection/voxel_rcnn/voxel_rcnn.py
Labels: bug

#169 [Feature] Support quant
  configs/quant/centerpoint_kitti.yml
  configs/quant/smoke_kitti.yml
  deploy/centerpoint/python/infer.py
  paddle3d/models/base/__init__.py
  paddle3d/models/base/base_detection.py
  paddle3d/models/base/base_model.py
  paddle3d/slim/__init__.py
  paddle3d/slim/quant.py
  requirements.txt
  tools/evaluate.py
  tools/export.py
  tools/graphvis.py
  tools/train.py
Labels: enhancement

#175 [Docs] update pvrcnn and voxelrcnn model and log file link docs
  docs/models/pv_rcnn/README.md
  docs/models/voxel_rcnn/README.md
Labels: documentation

#176 [Bug Fix] Fix petr train bug
  paddle3d/datasets/base.py
Labels: bug

#177 [Feature] Update PETR
  paddle3d/models/base/__init__.py
  paddle3d/models/base/base_model.py
  paddle3d/models/base/base_multiview_detection.py
  paddle3d/models/detection/petr/petr3d.py
  paddle3d/models/heads/dense_heads/petr_head.py
Labels: enhancement

#184 [Docs] Add quant docs
  configs/smoke/smoke_dla34_no_dcn_kitti_amp.yml
  docs/quickstart.md
  tools/train.py
Labels: documentation

#185 [Docs] Release v1.0
  docs/release_note.md
  paddle3d/__init__.py
Labels: documentation
