Repository PaddlePaddle/Paddle3D, pull requests merged in 2023-01, with the labels that each got.

#186 [Docs] add centerpoint trt python deploy explanation in docs
  docs/models/centerpoint/README.md
Labels: documentation

#194 [Docs] add centerpoint trt python deploy explanation in docs
  docs/models/centerpoint/README.md
Labels: documentation

#196 [Docs] add centerpoint trt python deploy explanation in docs
  docs/models/centerpoint/README.md
Labels: documentation

#197 [chery-pick] [Docs] add centerpoint trt python deploy explanation in docs
  docs/models/centerpoint/README.md
Labels: documentation

#188 [Feature] Optimize PETR multihead attention code
  paddle3d/models/layers/petr_transformer.py
  paddle3d/models/layers/transformer_layers.py
Labels: enhancement

#159 [Feature] Optimize sparse conv and voxelize
  deploy/centerpoint/cpp/custom_ops/voxelize_op.cu
  paddle3d/models/middle_encoders/sparse_resnet.py
  paddle3d/ops/voxel/voxelize_op.cu
Labels: enhancement

#208 [Bug Fix] Fix kitti eval bug
  paddle3d/datasets/kitti/kitti_utils.py
Labels: bug
